### PR TITLE
Fix dependency related issues such as cycles.

### LINKED ISSUE #98: Fix Backend Task logic dependency
In a minimum of 3 task there can apear indirect dependency, in that case a task cannot depend on a dependence of a parent task on any order of magnitude.
A proper error should be thrown in the backend to show to the user

Example:

a->b->c

c implicitly depends on a so you can not add a -> c

### PR DESCRIPTION
**Pull request by Feketics**
Fixed the issue where user could add any dependencies to a Task, which could result in cycles or other issues.
Closes issue #98

Only the Dockerfile and the taskServiceImpl were the files changed by me. Rest was done by spotless.

### CODE REVIEW

**Comment by Feketics** [comment]
Btw, ask Spotless why there are so many files changed. Might as well commit them too if it's gonna change them to be like this when run anyway.

File: BE/src/main/java/com/example/task/TaskServiceImpl.java [hunk 1]
```diff
@@ -214,4 +218,68 @@ public List<TaskDTO> getTasksAssignedToUser(Long userId) {
...
+            allTransitive.addAll(getAllTransitiveDependencies(parent.getId()));
+        }
+        // Check if any direct parent is in the transitive dependencies of other parents
+        for (Integer parentId : directParents) {
+            if (allTransitive.contains(parentId)) {
+                throw new IllegalArgumentException(
+                        "Cannot add task as dependency because it is an indirect dependency of another parent");
+            }
+        }
+    }
```
Comment (Real-Tristopher) [inline BE/src/main/java/com/example/task/TaskServiceImpl.java:255]: From the looks of it your repeated calling of getAllTransitiveDependencies would result in having duplicates of the same nodes since you're already getting all direct and indirect dependencies from the call on the initial, passed task.

Correct me if I'm wrong.

File: BE/src/main/java/com/example/task/TaskServiceImpl.java [hunk 2]
```diff
@@ -214,4 +218,68 @@ public List<TaskDTO> getTasksAssignedToUser(Long userId) {
...
+
+    private void throwIfCyclesInParents(Task task) {
+        Set<Integer> visited = new HashSet<>();
+        Set<Integer> recStack = new HashSet<>();
+        for (Task parent : task.getParents()) {
+            if (hasCycle(parent.getId(), visited, recStack)) {
+                throw new IllegalArgumentException("Dependencies contain cycles");
+            }
+        }
+    }
```
Comment (Real-Tristopher) [inline BE/src/main/java/com/example/task/TaskServiceImpl.java]: What is this for? This sort of check wouldn't be needed if we'd check for dependencies on all updates / inserts.

**Review by Real-Tristopher — CHANGES_REQUESTED** [review]
Other than what I've noted, you could get rid of the single letter variable names (there's a PMD rule for that, even if there weren't it'd still be nice) and use full words instead of shortened variants (recursive instead of rec)

File: BE/src/main/java/com/example/task/TaskServiceImpl.java (hunk 1 above)
Comment (Feketics) [reply BE/src/main/java/com/example/task/TaskServiceImpl.java:255]: No duplicates, since it is a set.

File: BE/src/main/java/com/example/task/TaskServiceImpl.java (hunk 2 above)
Comment (Feketics) [reply BE/src/main/java/com/example/task/TaskServiceImpl.java]: It's what it is for. In add operations to check the dependencies.

**Review by Real-Tristopher — APPROVED** [review]
Short on time; it's good enough and it works. Not entirely convinced by the author's point on throwIfParentsContainCycles.

**Review by x8hnc — APPROVED** [review]
lgtm
